package com.eas.designer.explorer.project.ui;

import com.eas.designer.application.project.PlatypusProject;
import com.eas.designer.application.project.PlatypusProjectSettings;
import java.awt.EventQueue;
import java.util.logging.Level;
import javax.swing.JPanel;
import org.openide.filesystems.FileObject;

/**
 *
 * @author mg
 */
public class PlatypusClientCustomizer extends JPanel {

    protected final PlatypusProject project;
    protected final FileObject appRoot;
    protected final PlatypusProjectSettings projectSettings;

    /**
     * Creates new form ProjectRunningCustomizer
     *
     * @param aProject
     */
    public PlatypusClientCustomizer(PlatypusProject aProject) {
        project = aProject;
        appRoot = aProject.getSrcRoot();
        projectSettings = aProject.getSettings();
        initComponents();
        EventQueue.invokeLater(() -> {
            if (projectSettings.getPlatypusClientUrl() != null) {
                txtClientUrl.setText(projectSettings.getPlatypusClientUrl());
            }
            if (projectSettings.getPlatypusClientRunCommand() != null) {
                txtClientRunCommand.setText(projectSettings.getPlatypusClientRunCommand());
            }
            cbClientLogLevel.setSelectedItem(projectSettings.getPlatypusClientLogLevel());
            spClientDebugPort.setValue(projectSettings.getPlatypusClientDebugPort());
        });
    }

    private Level[] getLogLevels() {
        return new Level[]{Level.SEVERE, Level.WARNING, Level.INFO, Level.CONFIG, Level.FINE, Level.FINER, Level.FINEST};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClientUrl = new javax.swing.JLabel();
        txtClientUrl = new javax.swing.JTextField();
        lblClientLogLevel = new javax.swing.JLabel();
        cbClientLogLevel = new javax.swing.JComboBox();
        lblClientDebugPort = new javax.swing.JLabel();
        spClientDebugPort = new javax.swing.JSpinner();
        lblClientRunCommand = new javax.swing.JLabel();
        txtClientRunCommand = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblClientUrl.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientUrl.text")); // NOI18N

        txtClientUrl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientUrlFocusLost(evt);
            }
        });
        txtClientUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientUrlActionPerformed(evt);
            }
        });

        lblClientLogLevel.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientLogLevel.text")); // NOI18N

        cbClientLogLevel.setModel(new javax.swing.DefaultComboBoxModel(getLogLevels()));
        cbClientLogLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientLogLevelItemStateChanged(evt);
            }
        });
        cbClientLogLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientLogLevelActionPerformed(evt);
            }
        });

        lblClientDebugPort.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientDebugPort.text")); // NOI18N

        spClientDebugPort.setMinimumSize(new java.awt.Dimension(36, 26));
        spClientDebugPort.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spClientDebugPortStateChanged(evt);
            }
        });
        spClientDebugPort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spClientDebugPortFocusLost(evt);
            }
        });

        lblClientRunCommand.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientRunCommand.text")); // NOI18N

        txtClientRunCommand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientRunCommandFocusLost(evt);
            }
        });
        txtClientRunCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientRunCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientRunCommand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClientRunCommand)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblClientDebugPort, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(lblClientUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClientLogLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbClientLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spClientDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 362, Short.MAX_VALUE))
                    .addComponent(txtClientUrl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientUrl)
                .addGap(4, 4, 4)
                .addComponent(txtClientUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientLogLevel)
                    .addComponent(cbClientLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spClientDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(lblClientRunCommand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientRunCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientUrlActionPerformed
        projectSettings.setPlatypusClientUrl(txtClientUrl.getText());
    }//GEN-LAST:event_txtClientUrlActionPerformed

    private void txtClientUrlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientUrlFocusLost
        projectSettings.setPlatypusClientUrl(txtClientUrl.getText());
    }//GEN-LAST:event_txtClientUrlFocusLost

    private void spClientDebugPortStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spClientDebugPortStateChanged
        projectSettings.setPlatypusClientDebugPort((int) spClientDebugPort.getValue());
    }//GEN-LAST:event_spClientDebugPortStateChanged

    private void spClientDebugPortFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spClientDebugPortFocusLost
        projectSettings.setPlatypusClientDebugPort((int) spClientDebugPort.getValue());
    }//GEN-LAST:event_spClientDebugPortFocusLost

    private void cbClientLogLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientLogLevelItemStateChanged
        projectSettings.setPlatypusClientLogLevel((Level) cbClientLogLevel.getSelectedItem());
    }//GEN-LAST:event_cbClientLogLevelItemStateChanged

    private void cbClientLogLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientLogLevelActionPerformed
        projectSettings.setPlatypusClientLogLevel((Level) cbClientLogLevel.getSelectedItem());
    }//GEN-LAST:event_cbClientLogLevelActionPerformed

    private void txtClientRunCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientRunCommandActionPerformed
        projectSettings.setPlatypusClientRunCommand(txtClientRunCommand.getText());
    }//GEN-LAST:event_txtClientRunCommandActionPerformed

    private void txtClientRunCommandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientRunCommandFocusLost
        projectSettings.setPlatypusClientRunCommand(txtClientRunCommand.getText());
    }//GEN-LAST:event_txtClientRunCommandFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbClientLogLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClientDebugPort;
    private javax.swing.JLabel lblClientLogLevel;
    private javax.swing.JLabel lblClientRunCommand;
    private javax.swing.JLabel lblClientUrl;
    private javax.swing.JSpinner spClientDebugPort;
    private javax.swing.JTextField txtClientRunCommand;
    private javax.swing.JTextField txtClientUrl;
    // End of variables declaration//GEN-END:variables
}
