package com.eas.designer.explorer.project.ui;

import com.eas.designer.application.project.PlatypusProject;
import com.eas.designer.application.project.PlatypusProjectSettings;
import java.awt.EventQueue;
import java.util.logging.Level;
import org.openide.filesystems.FileObject;

/**
 *
 * @author mg
 */
public class PlatypusClientCustomizer extends javax.swing.JPanel {

    protected final PlatypusProject project;
    protected final FileObject appRoot;
    protected final PlatypusProjectSettings projectSettings;

    /**
     * Creates new form ProjectRunningCustomizer
     *
     * @param aProject
     */
    public PlatypusClientCustomizer(PlatypusProject aProject) {
        project = aProject;
        appRoot = aProject.getSrcRoot();
        projectSettings = aProject.getSettings();
        initComponents();
        EventQueue.invokeLater(() -> {
            if (projectSettings.getRunUser() != null) {
                txtUserName.setText(projectSettings.getRunUser());
            }
            if (projectSettings.getRunPassword() != null) {
                txtPassword.setText(projectSettings.getRunPassword());
            }
            if (projectSettings.getPlatypusClientOptions() != null) {
                txtClientOptions.setText(projectSettings.getPlatypusClientOptions());
            }
            if (projectSettings.getPlatypusClientVmOptions() != null) {
                txtClientVmOptions.setText(projectSettings.getPlatypusClientVmOptions());
            }
            if (projectSettings.getPlatypusClientUrl() != null) {
                txtClientUrl.setText(projectSettings.getPlatypusClientUrl());
            }
            if (projectSettings.getPlatypusClientRunCommand() != null) {
                txtClientRunCommand.setText(projectSettings.getPlatypusClientRunCommand());
            }
            cbClientLogLevel.setSelectedItem(projectSettings.getPlatypusClientLogLevel());
            spClientDebugPort.setValue(projectSettings.getPlatypusClientDebugPort());
        });
    }

    private Level[] getLogLevels() {
        return new Level[]{Level.SEVERE, Level.WARNING, Level.INFO, Level.CONFIG, Level.FINE, Level.FINER, Level.FINEST};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClientUrl = new javax.swing.JLabel();
        txtClientUrl = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblClientOptions = new javax.swing.JLabel();
        txtClientOptions = new javax.swing.JTextField();
        lblClientVmOptions = new javax.swing.JLabel();
        txtClientVmOptions = new javax.swing.JTextField();
        lblClientLogLevel = new javax.swing.JLabel();
        cbClientLogLevel = new javax.swing.JComboBox();
        lblClientDebugPort = new javax.swing.JLabel();
        spClientDebugPort = new javax.swing.JSpinner();
        lblClientRunCommand = new javax.swing.JLabel();
        txtClientRunCommand = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblClientUrl.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientUrl.text")); // NOI18N

        txtClientUrl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientUrlFocusLost(evt);
            }
        });
        txtClientUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientUrlActionPerformed(evt);
            }
        });

        lblUserName.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblUserName.text")); // NOI18N

        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblPassword.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblPassword.text")); // NOI18N

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblClientOptions.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientOptions.text")); // NOI18N

        txtClientOptions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientOptionsFocusLost(evt);
            }
        });
        txtClientOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientOptionsActionPerformed(evt);
            }
        });

        lblClientVmOptions.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientVmOptions.text")); // NOI18N

        txtClientVmOptions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientVmOptionsFocusLost(evt);
            }
        });
        txtClientVmOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientVmOptionsActionPerformed(evt);
            }
        });

        lblClientLogLevel.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientLogLevel.text")); // NOI18N

        cbClientLogLevel.setModel(new javax.swing.DefaultComboBoxModel(getLogLevels()));
        cbClientLogLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientLogLevelItemStateChanged(evt);
            }
        });
        cbClientLogLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientLogLevelActionPerformed(evt);
            }
        });

        lblClientDebugPort.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientDebugPort.text")); // NOI18N

        spClientDebugPort.setMinimumSize(new java.awt.Dimension(36, 26));
        spClientDebugPort.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spClientDebugPortStateChanged(evt);
            }
        });
        spClientDebugPort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spClientDebugPortFocusLost(evt);
            }
        });

        lblClientRunCommand.setText(org.openide.util.NbBundle.getMessage(PlatypusClientCustomizer.class, "PlatypusClientCustomizer.lblClientRunCommand.text")); // NOI18N

        txtClientRunCommand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientRunCommandFocusLost(evt);
            }
        });
        txtClientRunCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientRunCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblClientDebugPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClientOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClientVmOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClientUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClientLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spClientDebugPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbClientLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(371, 371, 371))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClientOptions, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword)
                                    .addComponent(txtClientVmOptions, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtClientUrl))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClientRunCommand, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientRunCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientUrl)
                    .addComponent(txtClientUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientOptions)
                    .addComponent(txtClientOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientVmOptions)
                    .addComponent(txtClientVmOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientLogLevel)
                    .addComponent(cbClientLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblClientDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spClientDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblClientRunCommand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientRunCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientOptionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientOptionsFocusLost
        projectSettings.setPlatypusClientOptions(txtClientOptions.getText());
    }//GEN-LAST:event_txtClientOptionsFocusLost

    private void txtClientOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientOptionsActionPerformed
        projectSettings.setPlatypusClientOptions(txtClientOptions.getText());
    }//GEN-LAST:event_txtClientOptionsActionPerformed

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        projectSettings.setRunUser(txtUserName.getText());
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        projectSettings.setRunUser(txtUserName.getText());
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        projectSettings.setRunPassword(new String(txtPassword.getPassword()));
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        projectSettings.setRunPassword(new String(txtPassword.getPassword()));
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtClientUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientUrlActionPerformed
        projectSettings.setPlatypusClientUrl(txtClientUrl.getText());
    }//GEN-LAST:event_txtClientUrlActionPerformed

    private void txtClientUrlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientUrlFocusLost
        projectSettings.setPlatypusClientUrl(txtClientUrl.getText());
    }//GEN-LAST:event_txtClientUrlFocusLost

    private void txtClientVmOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientVmOptionsActionPerformed
        projectSettings.setPlatypusClientVmOptions(txtClientVmOptions.getText());
    }//GEN-LAST:event_txtClientVmOptionsActionPerformed

    private void txtClientVmOptionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientVmOptionsFocusLost
        projectSettings.setPlatypusClientVmOptions(txtClientVmOptions.getText());
    }//GEN-LAST:event_txtClientVmOptionsFocusLost

    private void spClientDebugPortStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spClientDebugPortStateChanged
        projectSettings.setPlatypusClientDebugPort((int) spClientDebugPort.getValue());
    }//GEN-LAST:event_spClientDebugPortStateChanged

    private void spClientDebugPortFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spClientDebugPortFocusLost
        projectSettings.setPlatypusClientDebugPort((int) spClientDebugPort.getValue());
    }//GEN-LAST:event_spClientDebugPortFocusLost

    private void cbClientLogLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientLogLevelItemStateChanged
        projectSettings.setPlatypusClientLogLevel((Level) cbClientLogLevel.getSelectedItem());
    }//GEN-LAST:event_cbClientLogLevelItemStateChanged

    private void cbClientLogLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientLogLevelActionPerformed
        projectSettings.setPlatypusClientLogLevel((Level) cbClientLogLevel.getSelectedItem());
    }//GEN-LAST:event_cbClientLogLevelActionPerformed

    private void txtClientRunCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientRunCommandActionPerformed
        projectSettings.setPlatypusClientRunCommand(txtClientRunCommand.getText());
    }//GEN-LAST:event_txtClientRunCommandActionPerformed

    private void txtClientRunCommandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientRunCommandFocusLost
        projectSettings.setPlatypusClientRunCommand(txtClientRunCommand.getText());
    }//GEN-LAST:event_txtClientRunCommandFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbClientLogLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClientDebugPort;
    private javax.swing.JLabel lblClientLogLevel;
    private javax.swing.JLabel lblClientOptions;
    private javax.swing.JLabel lblClientRunCommand;
    private javax.swing.JLabel lblClientUrl;
    private javax.swing.JLabel lblClientVmOptions;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JSpinner spClientDebugPort;
    private javax.swing.JTextField txtClientOptions;
    private javax.swing.JTextField txtClientRunCommand;
    private javax.swing.JTextField txtClientUrl;
    private javax.swing.JTextField txtClientVmOptions;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
