package com.eas.designer.explorer.project.ui;

import com.eas.designer.explorer.project.PlatypusProjectImpl;
import com.eas.designer.explorer.project.PlatypusProjectSettingsImpl;
import java.awt.EventQueue;
import org.openide.filesystems.FileObject;

/**
 *
 * @author mg
 */
public class ServletContainerCustomizer extends javax.swing.JPanel {

    protected final PlatypusProjectImpl project;
    protected final FileObject appRoot;
    protected final PlatypusProjectSettingsImpl projectSettings;

    /**
     * Creates new form ProjectRunningCustomizer
     */
    public ServletContainerCustomizer(PlatypusProjectImpl aProject) throws Exception {
        project = aProject;
        appRoot = aProject.getSrcRoot();
        projectSettings = aProject.getSettings();
        initComponents();
        EventQueue.invokeLater(() -> {
            cbEnableWebSecurity.setSelected(projectSettings.isSecurityRealmEnabled());
            cbAutoApply.setSelected(projectSettings.isAutoApplyWebSettings());
            if (projectSettings.getServerContext() != null) {
                txtContext.setText(projectSettings.getServerContext());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContext = new javax.swing.JLabel();
        txtContext = new javax.swing.JTextField();
        cbEnableWebSecurity = new javax.swing.JCheckBox();
        cbAutoApply = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblContext.setText(org.openide.util.NbBundle.getMessage(ServletContainerCustomizer.class, "ServletContainerCustomizer.lblContext.text")); // NOI18N

        txtContext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContextFocusLost(evt);
            }
        });
        txtContext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContextActionPerformed(evt);
            }
        });

        cbEnableWebSecurity.setText(org.openide.util.NbBundle.getMessage(ServletContainerCustomizer.class, "ServletContainerCustomizer.cbEnableWebSecurity.text")); // NOI18N
        cbEnableWebSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnableWebSecurityActionPerformed(evt);
            }
        });

        cbAutoApply.setText(org.openide.util.NbBundle.getMessage(ServletContainerCustomizer.class, "ServletContainerCustomizer.cbAutoApply.text")); // NOI18N
        cbAutoApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAutoApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEnableWebSecurity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAutoApply, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblContext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContext)
                    .addComponent(txtContext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEnableWebSecurity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAutoApply)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContextActionPerformed
        projectSettings.setServerContext(txtContext.getText());
    }//GEN-LAST:event_txtContextActionPerformed

    private void txtContextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContextFocusLost
        projectSettings.setServerContext(txtContext.getText());
    }//GEN-LAST:event_txtContextFocusLost

    private void cbEnableWebSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnableWebSecurityActionPerformed
        projectSettings.setSecurityRealmEnabled(cbEnableWebSecurity.isSelected());
    }//GEN-LAST:event_cbEnableWebSecurityActionPerformed

    private void cbAutoApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAutoApplyActionPerformed
        projectSettings.setAutoApplyWebSettings(cbAutoApply.isSelected());
    }//GEN-LAST:event_cbAutoApplyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAutoApply;
    private javax.swing.JCheckBox cbEnableWebSecurity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContext;
    private javax.swing.JTextField txtContext;
    // End of variables declaration//GEN-END:variables
}
